#!/usr/bin/env python3
"""
Generates src/styles/cityPalette.js and src/data/cityColorMap.js.

Run from project root:
    python3 tools/data_transformation/build_city_color_map.py
Or via npm:
    npm run gen:city-colors

Re-run whenever jurisdictions.json gains new entries. Both output files
should be committed to the repo — they are static artifacts, not computed at runtime.
"""

import json
import colorsys
import math
from pathlib import Path

ROOT = Path(__file__).parent.parent.parent
JURISDICTIONS_FILE = ROOT / "data" / "processed" / "jurisdictions.json"
OUT_PALETTE = ROOT / "src" / "styles" / "cityPalette.js"
OUT_MAP = ROOT / "src" / "data" / "cityColorMap.js"

# 20 base hues: (name, hue_degrees, s_min, s_max)
# Vivid hues: s range ~65-90%; muted neutrals: s range ~18-40%
HUES = [
    ("cyan",    185, 65, 88),
    ("teal",    174, 65, 88),
    ("emerald", 152, 60, 85),
    ("lime",     84, 58, 82),
    ("yellow",   50, 72, 92),
    ("amber",    38, 78, 92),
    ("orange",   24, 75, 90),
    ("coral",    12, 68, 86),
    ("rose",    354, 65, 85),
    ("pink",    340, 62, 82),
    ("fuchsia", 300, 65, 85),
    ("violet",  270, 62, 82),
    ("purple",  255, 62, 82),
    ("indigo",  240, 65, 85),
    ("blue",    220, 68, 88),
    ("sky",     200, 68, 88),
    ("sage",    140, 22, 38),   # muted
    ("slate",   215, 18, 32),   # muted
    ("stone",    30, 16, 30),   # muted
    ("sand",     45, 20, 35),   # muted
]


def hsl_to_hex(h_deg, s_pct, l_pct):
    # colorsys uses HLS (hue, lightness, saturation) — note parameter order
    r, g, b = colorsys.hls_to_rgb(h_deg / 360.0, l_pct / 100.0, s_pct / 100.0)
    return "#{:02x}{:02x}{:02x}".format(
        max(0, min(255, round(r * 255))),
        max(0, min(255, round(g * 255))),
        max(0, min(255, round(b * 255))),
    )


def build_palette():
    """Returns ordered list of (token_name, hex_value) tuples — 400 total."""
    entries = []
    for hue_name, hue_deg, s_min, s_max in HUES:
        for i in range(1, 21):
            t = (i - 1) / 19.0
            # Lightness: 18% (dark) → 94% (light)
            L = 18 + t * 76
            # Saturation: arc that peaks near midtone (t≈0.4), backs off at extremes
            arc = 1.0 - abs(t - 0.4) / 0.6
            S = s_min + (s_max - s_min) * arc
            S = min(S, s_max)
            token = f"{hue_name}_{i:02d}"
            entries.append((token, hsl_to_hex(hue_deg, S, L)))
    return entries


def write_palette_file(palette_entries):
    lines = [
        "// src/styles/cityPalette.js",
        "// AUTO-GENERATED by tools/data_transformation/build_city_color_map.py",
        "// DO NOT EDIT BY HAND — run `npm run gen:city-colors` to regenerate.",
        "//",
        "// 400 color tokens: 20 base hues × 20 shades each.",
        "// Shade 01 = darkest (~18% lightness), shade 20 = lightest (~94% lightness).",
        "",
        "export const CITY_PALETTE = {",
    ]
    for token, hex_val in palette_entries:
        lines.append(f'  {token}: "{hex_val}",')
    lines.append("};")
    lines.append("")
    OUT_PALETTE.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(palette_entries)} tokens → {OUT_PALETTE.relative_to(ROOT)}")


def write_map_file(palette_entries, city_keys):
    token_names = [t for t, _ in palette_entries]
    mapping = {key: token_names[i % len(token_names)] for i, key in enumerate(city_keys)}

    palette_dict = dict(palette_entries)

    lines = [
        "// src/data/cityColorMap.js",
        "// AUTO-GENERATED by tools/data_transformation/build_city_color_map.py",
        "// DO NOT EDIT BY HAND — run `npm run gen:city-colors` to regenerate.",
        "//",
        "// Assignment: alphabetical sort of jurisdictions.json keys, round-robin across 400 palette tokens.",
        "// City key format: \"CityName|CA\" (matches CITY_DATA key format in src/data/cities.js).",
        "",
        "import { CITY_PALETTE } from '../styles/cityPalette.js'",
        "",
        "const FALLBACK_COLOR = '#d1d5db' // --gray-300",
        "",
        "export const CITY_COLOR_MAP = {",
    ]
    for key, token in mapping.items():
        lines.append(f'  "{key}": "{token}",')
    lines.append("};")
    lines.append("")
    lines.append("export function getCityColor(cityKey) {")
    lines.append("  const token = CITY_COLOR_MAP[cityKey]")
    lines.append("  if (!token) return FALLBACK_COLOR")
    lines.append("  return CITY_PALETTE[token] ?? FALLBACK_COLOR")
    lines.append("}")
    lines.append("")
    OUT_MAP.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(mapping)} city mappings → {OUT_MAP.relative_to(ROOT)}")


def main():
    jurisdictions = json.loads(JURISDICTIONS_FILE.read_text(encoding="utf-8"))
    city_keys = sorted(f"{name}|CA" for name in jurisdictions.keys())
    print(f"Found {len(city_keys)} jurisdictions in jurisdictions.json")

    palette_entries = build_palette()
    write_palette_file(palette_entries)
    write_map_file(palette_entries, city_keys)
    print("Done.")


if __name__ == "__main__":
    main()
